### ISSUE TITLE
tasks, boosts and new upgrades available

### ISSUE THREAD

**Issue by oleks-kr** [TemoSulava/1win-tapper-claimer#1]
are you planning to add them?
![photo_2024-08-03 14 55 44](https://github.com/user-attachments/assets/9aed6fcb-e155-46ae-af78-9902b1dd0e52)
![photo_2024-08-03 14 55 47](https://github.com/user-attachments/assets/75cbeb9c-c465-47b5-9bdc-84f6eacbd0e5)

**Comment by TemoSulava** [comment]
Yes, but not quite sure when. i don't have much time rn
